### ISSUE TITLE
Blinking Cursor Disappears in Light Mode

### ISSUE THREAD

**Issue by ClaireBookworm** [notion-enhancer/notion-enhancer#229]
Title ^^ the cursor is there in dark mode but disappears in light mode (most likely because the blinking thing is white and blends in...)

I'm on MacOS desktop and here's a screenshot:
<img width="680" alt="Screen Shot 2020-11-07 at 12 41 42 PM" src="https://user-images.githubusercontent.com/41759033/98450999-b6738600-20f6-11eb-8626-60b67b28f81f.png">

Changing to dark mode fixes it.

**Comment by dragonwocky** [comment]
did you happen to have tabs enabled? this may have been a problem where the tab didn't focus properly and so the cursor didn't show up, because the cursor is black/visible when i just tested normally.

if it was the former then I'm marking this as fixed in the work-in-progress.

**Comment by anup514** [comment]
@dragonwocky I've had this issue for weeks (still not resolved), and I _just_ found out that I could do multiple tabs. So tabs is clearly not the issue here.

**Comment by anup514** [comment]
@ClaireBookworm It _is_ because the blinking thing is white and is blending in. I've tried re-installing the app, still not visible. I did a screen recording of the issue, but the cursor becomes visible in the recording somehow😆.
I have Notion 2.0.39

**Comment by dragonwocky** [comment]
@anup514 I suspect there's two causes of what appears to very similar behaviour here: tab focus causing the cursor to be missing entirely (which was definitely happening and was fixed after this issue was opened), and a bug in the theming system turning the cursor white (which I think is what you're experiencing). Instead of bumping an issue that's already been closed for over 2 years, could you please open a new issue about it?

**Comment by agnashetty** [comment]
Go to settings -> Accessibility -> Mouse pointer & touch. Then change the mouse pointer style to Dark. that should fix the issue.
(System settings and not notion setting)

**Comment by dmtiblin** [comment]
> Go to settings -> Accessibility -> Mouse pointer & touch. Then change the mouse pointer style to Dark. that should fix the issue.

Is this mouse fix still available? I don't have this option in settings, I can only choose between light mode/dark mode for the whole app. I hate dark mode but the disappearing mouse is equally horrible...

**Comment by dragonwocky** [comment]
@dmtiblin the option is under system settings, not within Notion settings. On Windows it's under Accessibility > Mouse pointer and touch > Mouse pointer style, on macOS it's under Accessibility > Display > Pointer.
