### ISSUE TITLE
close/minimise/maximise/hide buttons in Notion Enhancer

### ISSUE THREAD

**Issue by xSVTx** [notion-enhancer/notion-enhancer#366]
**describe the bug**
close/minimize/maximize/hide buttons have disappeared completely.

**expected behavior**
It's simple - Buttons must be on the screen.

**screenshots**
![image](https://user-images.githubusercontent.com/40675707/103485630-ce226e80-4e08-11eb-88b6-b74548080abb.png)

**platform**
Windows 10

**Comment by joshdavies14** [comment]
This is definitely a known issue that I believe was fixed? I can normally get them back if I go to a different page and then relaunch from the tray icon (for some reason it only works on certain pages for me, and sometimes you need to relaunch a couple of times)

**Comment by frankjlin16** [comment]
Hello, first of all, I got to say I absolutely love this project. However, I'm having this issue as well. Sometimes the buttons show up, but sometimes I would have to restart the program multiple times. The problem seems to be getting more intense by the day. I'm not sure if a clean uninstall/install would do the trick, but if there's a way to fix this issue, I'd rather go that route. Cheers!

**Comment by dragonwocky** [comment]
hm, I thought this was fixed.
can you check the console when this happens and tell me of any errors in there? (`ctrl+shift+i`)

**Comment by xSVTx** [comment]
![image](https://user-images.githubusercontent.com/40675707/103511627-7885aa80-4e78-11eb-87a1-559759bcb4a5.png)
![image](https://user-images.githubusercontent.com/40675707/103512265-7a03a280-4e79-11eb-90fa-078546900ca0.png)
The problem comes from core/css/buttons.css on line 127
The operation cannot be performed because the property "appendChild" is NULL.

**Comment by frankjlin16** [comment]
@dragonwocky Here's the console errors you asked for. I don't know which one of these is the one causing the problem, but hopefully, this is what you are asking for.

[www.notion.so-1609783109827.log](https://github.com/notion-enhancer/notion-enhancer/files/5766110/www.notion.so-1609783109827.log)
![Screenshot 2021-01-04 105400](https://user-images.githubusercontent.com/67761168/103564587-00b97f00-4e7c-11eb-8fcf-c5c14b150e77.png)

**Comment by frankjlin16** [comment]
Hey, just a little update. The issue resolves itself after a quick refresh (`ctrl+r`). However, the issue still exists upon initial opening sometimes.

**Comment by dragonwocky** [comment]
try replacing line 108 in `mods/core/client.js` with `!document.querySelector('.notion-topbar > div[style*="display: flex"]')`.

**Comment by frankjlin16** [comment]
Haven't had issues for 2 days. Looks like that sprinkle of magical dust fixed it. Thanks! @dragonwocky

**Comment by ijahehehehe** [comment]
![image](https://user-images.githubusercontent.com/117549444/200147804-a50625d5-917a-43b3-bfb3-d25046e12f59.png)
been struggling with the same issue for a month, please kindly help solve this

**Comment by ijahehehehe** [comment]
> ![image](https://user-images.githubusercontent.com/117549444/200147804-a50625d5-917a-43b3-bfb3-d25046e12f59.png) been struggling with the same issue for a month, please kindly help solve this

@dragonwocky

**Comment by dragonwocky** [comment]
@ijahehehehe please don't bump closed issues, this was an old issue from a previous version of notion and the notion-enhancer that has since been resolved. If you are having problems with the current version of the notion-enhancer please create a new issue with information about what's going on.
